import Head from 'next/head'
import { Inter } from 'next/font/google'
import CallToActionWithAnnotation from './components/prouthero'
import { NextPageContext } from 'next'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CallToActionWithAnnotation title={props.data.test} />
      </main>
    </>
  )
}

// This gets called on every request
export async function getServerSideProps(context: NextPageContext) {

  const data = context.query
  // Pass data to the page via props
  return { props: { data } }
}