import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import WithSubnavigation from './components/navbar'
import CallToActionWithIllustration from './components/hero'
import LargeWithLogoCentered from './components/footer'
import { NextPageContext } from 'next'
import CallToActionWithAnnotation from './components/prouthero'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
  console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WithSubnavigation />
        <CallToActionWithIllustration />
        <LargeWithLogoCentered />
      </main>
    </>
  )
}